CREATE TABLE `users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `level` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `sdt` VARCHAR(11) DEFAULT NULL,
  `dia_chi` LONGTEXT,
  `status` VARCHAR(255) NOT NULL DEFAULT '1',
  `password` VARCHAR(255) NOT NULL,
  `fullname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `avatar` VARCHAR(255),
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `remember_token` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `uploaded_files` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NOT NULL,
  `file_path` VARCHAR(255) NOT NULL,
  `original_name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`id_user`) REFERENCES `users`(`id`) ON DELETE CASCADE
)

CREATE TABLE `questions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_file` INT(11) NOT NULL,
  `content` VARCHAR(1000) NOT NULL,
  `option_1` VARCHAR(255) NOT NULL,
  `option_2` VARCHAR(255) NOT NULL,
  `option_3` VARCHAR(255) NOT NULL,
  `option_4` VARCHAR(255) NOT NULL,
  `answer` VARCHAR(255) NOT NULL,
  `level` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`id_file`) REFERENCES `uploaded_files`(`id`) ON DELETE CASCADE
)
