CREATE TABLE `users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `level` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `sdt` VARCHAR(11) DEFAULT NULL,
  `dia_chi` LONGTEXT,
  `status` VARCHAR(255) NOT NULL DEFAULT '1',
  `password` VARCHAR(255) NOT NULL,
  `fullname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `remember_token` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
);
